---
title: "iid_model"
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
#| include: false

knitr::opts_chunk$set(echo = TRUE, results = "markup")

## packages
pkgs <- c(
  "cmdstanr", "tidyverse", "RColorBrewer", "patchwork",
  "brms", "tidybayes", "bayesplot", "future", "parallel", "rstan"
)
vapply(
  pkgs, library, logical(1), character.only = TRUE, logical.return = TRUE
)

## stan settings
rstan_options(auto_write = TRUE)

## plot settings
theme_set(
  theme_bw() +
    theme(text = element_text(size = 18, face = "bold"), 
          title = element_text(size = 18, face = "bold"),
          legend.position = "bottom")
)

## Set options (removed mc.cores = , as I now put this in the model fit function)
options(
  brms.backend = "cmdstanr",
  future.fork.enable = TRUE,
  future.rng.onMisuse = "ignore"
)

## Detect machine capabilities
parallel::detectCores()  # Should be 28

supportsMulticore()
```

# 1. read in the data

```{r}
#| label: read-wrangle

# read in posterior medians and cambridge scores
theta_pid_q <- read_csv(
  here("data", "theta_pid_q.csv"),
  show_col_types = FALSE
)
cam_face <- read_csv(
  here("data", "cambridge_acc_scores_pid.csv"),
  show_col_types = FALSE
) |>
  filter(task == "face") |>
  rename(face_recog = n_correct) |>
  mutate(face = face_recog - mean(face_recog, na.rm = TRUE)) |>
  select(pid, face)

cam_car <- read_csv(
  here("data", "cambridge_acc_scores_pid.csv"),
  show_col_types = FALSE
) |>
  filter(task == "car") |>
  rename(car_recog = n_correct) |>
  mutate(car = car_recog - mean(car_recog, na.rm = TRUE)) |>
  select(pid, car)

# drift rate data — same structure as pilot
drift_data <- theta_pid_q |>
  filter(str_detect(param, "v_S")) |>
  select(pid, param, value) |>
  mutate(
    stimulus = if_else(str_detect(param, "novel"), "novel", "learned"),
    accuracy = if_else(str_detect(param, "TRUE"), "true", "false"),
    condition = factor(
      paste0(stimulus, ".", accuracy),
      levels = c("learned.false", "novel.false", "learned.true", "novel.true")
    ),
    stimulus = factor(stimulus, levels = c("learned", "novel")),
    accuracy = factor(accuracy, levels = c("false", "true"))
  ) |>
  left_join(cam_face, by = "pid") |>
  left_join(cam_car, by = "pid") |>
  select(pid, condition, stimulus, accuracy, face, car, value)

# threshold data
thresh_data <- theta_pid_q |>
  filter(str_detect(param, "B_")) |>
  select(pid, param, value) |>
  mutate(
    response = if_else(str_detect(param, "novel"), "novel", "learned"),
    response = factor(response, levels = c("learned", "novel"))
  ) |>
  left_join(cam_face, by = "pid") |>
  left_join(cam_car, by = "pid") |>
  select(pid, response, face, car, value)

# check structure
head(drift_data)
head(thresh_data)
```

# 2. read in models (if previously computed)

```{r}
#| label: read-models
#| eval: false

b1_drift <- readRDS("models/b1_drift.rds")
b2_drift <- readRDS("models/b2_drift.rds")

b1_thresh <- readRDS("models/b1_thresh.rds")
b2_thresh <- readRDS("models/b2_thresh.rds")
```

# 3. fit some models

## set defaults and create a function

```{r}
#| label: brms-defaults-function

brm_defaults <- list(
  family = gaussian(),
  iter = 2000,
  warmup = 1000,
  cores = 10,
  chains = 4,
  save_pars = save_pars(all = TRUE),
  seed = 123,
  control = list(adapt_delta = 0.95, max_treedepth = 15)
)

fit_model <- function(formula, prior, file, data, ...) {
  brm(
    formula = formula,
    prior = prior,
    file = file,
    data = data,  
    family = brm_defaults$family,
    iter = brm_defaults$iter,
    warmup = brm_defaults$warmup,
    cores = brm_defaults$cores,
    chains = brm_defaults$chains,
    save_pars = brm_defaults$save_pars,
    seed = brm_defaults$seed,
    control = brm_defaults$control,
    ...
  )
}
```

## drift rate

### fit model b1

```{r}
dsic#| label: fit-b1-drift

## formula
formula = bf(value ~ 0 + condition + condition:face)

## check priors
get_prior(formula, data = drift_data, family = gaussian())

## set priors
priors <- c(
  set_prior("normal(3, 1)", class = "b"),
  set_prior("normal(0, 1)", class = "b", coef = c("conditionlearned.false:face",
                                                  "conditionlearned.true:face",
                                                  "conditionnovel.false:face",
                                                  "conditionnovel.true:face")),
  set_prior("normal(0, 1)", class = "sigma")
)

## fit the model
b1_drift <- fit_model(
  formula = formula,
  prior = priors,
  data = drift_data,
  file = "models/b1_drift",
)

summary(b1_drift)
```

### fit model b2

```{r}
#| label: fit-b2-drift

## formula
formula = bf(value ~ 0 + condition + condition:face + condition:car)

## check priors
get_prior(formula, data = drift_data, family = gaussian())

## set priors
priors <- c(
  set_prior("normal(3, 1)", class = "b"),
  set_prior("normal(0, 1)", class = "b", coef = c("conditionlearned.false:face",
                                                  "conditionlearned.true:face",
                                                  "conditionnovel.false:face",
                                                  "conditionnovel.true:face",
                                                  "conditionlearned.false:car",
                                                  "conditionlearned.true:car",
                                                  "conditionnovel.false:car",
                                                  "conditionnovel.true:car")),
  set_prior("normal(0, 1)", class = "sigma")
)

## fit the model
b2_drift <- fit_model(
  formula = formula,
  prior = priors,
  data = drift_data,
  file = "models/b2_drift",
)

summary(b2_drift)
```

## threshold 

### fit model b1

```{r}
#| label: fit-b1-thresh

## formula
formula = bf(value ~ 0 + response + response:face)

## check priors
get_prior(formula, data = thresh_data, family = gaussian())

## set priors
priors <- c(
  set_prior("normal(2, 1)", class = "b"),
  set_prior("normal(0, 1)", class = "b", coef = c("responselearned:face",
                                                  "responsenovel:face")),
  set_prior("normal(0, 1)", class = "sigma")
)

## fit the model
b1_thresh <- fit_model(
  formula = formula,
  prior = priors,
  data = thresh_data,
  file = "models/b1_thresh",
)

summary(b1_thresh)
```

### fit model b2

```{r}
#| label: fit-b2-thresh

## formula
formula = bf(value ~ 0 + response + response:face + response:car)

## check priors
get_prior(formula, data = thresh_data, family = gaussian())

## set priors
priors <- c(
  set_prior("normal(2, 1)", class = "b"),
  set_prior("normal(0, 1)", class = "b", coef = c("responselearned:face",
                                                  "responsenovel:face",
                                                  "responselearned:car",
                                                  "responsenovel:car")),
  set_prior("normal(0, 1)", class = "sigma")
)

## fit the model
b2_thresh <- fit_model(
  formula = formula,
  prior = priors,
  data = thresh_data,
  file = "models/b2_thresh",
)

summary(b2_thresh)
```

# 4. Model checks and diagnostics

tbc

chains, rhat etc.