---
title: "Notes"
format: html
editor: visual
---

Thursday 09 July: Raph notes

Introduction - 3rd paragraph: I would like to explain a little more here the advantage of using computational approaches when investigating individual differences. And I don't really like the flow in this paragraph. I think that it is where I should pinpoint gaps in the literature regarding our research question but I don't really know how to tackle this. - 4th paragraph: I think the content is good but again, I think that the flow is strange.

Methods: - Figure of the face recognition task: this is not the correct figure since we used different face stimuli (cropped by the webmorph R Package). But it was just to show you that I am planning to add a figure there. I am currently working on the actual figure. - Data analysis: I don't really know into how much details I should go here. Should I mention all the correlations and plausible value correlations that we did? Or is what I wrote there enough?

Results: - Overall, the plots need polishing (plots size, text size...) but the information that we want to show is there. - I don't really know how much details I should add here in the text since I am providing summary tables. I tried to summarize the important results in the text, but not sure if that is enough. - Regression models: should I add a summary table with the coefficient from the model? In this section I just described visually the plots but since in the preregistered inferential criteria we decided to make our inferences based on the coefficient, I guess that we should include them as well and make our inferences based on them. What do you think? For now I did not add anything here since it is something that I think we should discuss.

Supplementary materials: here I am just doing a list of what should go in the supplementary - Parameter recovery study? - Model fit - RT and accuracy plots - Some correlations plots: accuracy task X Cambridge tests scores, Camrbidges Face scores X Cambridge Car scores - Regression model threshold + predictions

## July 20th - Rich notes

### Intro

P1 - consider ending this first para with an active statement about how the paper takes things forward. E.g/., in this paper, we use blah to study how ... One sentence. It might set the scene a little and give context on aims. P2 - r value ranging from 0 to 0.37 seems a little odd. Why not just say positive association but with modest effect sizes or reasonably small? Writing r=0 just seems odd to then say positive association. Make sense? Maybe break up para 2, as it is quite long. And connect with a broader and longer history of individual diffs (or differential psychology) in general. We discussed this in our last meeting. I can be brief - 1 or 2 sentences maybe that just makes the point that differntial psychology has a long history beyond face perception. P3 - I like the transition here. It works well. I would just clarify what you mean by "this model-based analysis". P4 - I also like this transition in general. Here I would just make the explicit link to this past work being from the experimental psychology tradition. e.g., differences between conditions or groups (rather than variation across individuals). Also, I think the first sentence needs a little work with past tense and grammar, but we can fix that later. P5 - This seems fine for now. We can polish later.

### methods and results

I didn't read the methods and results this time, since we discussed them at length in our past meeting.

### Discussion

I think the general structure works. But of course, we need a little more flow to make it easier to read.

I would do a few things here.

1.  Be disciplined in word count for the discussion, as this will make you select carefully which paragraphs are required and which can be relegated to a sentence or just removed.
2.  Decide on themes to cover as that will help you organise paragraphs. e.g., opening para - main contribution. Then theoretical advance etc. in the next paras, then limitations, future directions.
3.  As per the feedback for the intro, early on in the discussion, I would connect back to the broader theme of linking together experimental, differential and computational approaches to understand the cognitive processes that underpin face perception. Maybe even in the first para we could say this study shows how knowledge or novel insight can be gained from linking together blah blah and blah approaches. So we would be concluding something about the value of the method for the field, as well as the specific results.
4.  I would read the following Phillips and White paper and cite it. Maybe you meant to cite this already, but I could not see it. https://bpspsychub.onlinelibrary.wiley.com/doi/full/10.1111/bjop.12794 It is more about deep learning models, but there are many links nonetheless. I am sure it will help you think about the value of estimating latent variables and such like.


## July 29th - Raph notes

I think that a good stab at the manuscript at this point would be appreciated. Feel free to change it wherever you see fit and to add comments/notes as well. 

### Introduction:

I modified the intro in regards of your previous comments on it

Paragraph 4:  I would like to develop this paragraph a bit more but I don't really have any clear idea so some help on this would be great

### Methods:
- Correct figures for the face recognition task

### Results:
- Plots size: I think the plot size is good except for the Figure 6. The problem is that quarto does not handle different subfigure size very well. I would like the threshold subfigure to be smaller. I could do two different figures but I feel that it would add another figure and that it is not what we want. If you have any idea regarding this, I take it.

- Table for model summary: I don;t know if I should add a summary table of the linear model parameter after the two model figures. 

Overall I think that we could add some comments in the result section to just describe the results, more particularly for the linear model. But without a summary table to support the comment maybe it is not a good idea. What do you think?

###Discussion:
I think that the flow of the discussion is pretty good. I just have an issue with Paragraph 4 and one limitation:

- Paragraph 4: I don;t really know how to put this together. The idea here would be to show how our approach can extend previous model of face perception and memory (Ex: Bruce and Young model), but I cannot find a good flow for this paragraph. Also the fact that we did not mention Bruce and Young model in the introduction is bothering me. I find that this paragraph is very important but cannot find a way to show it.

- Limitations (effect size of correlations): here I would like to say that our effect size are low and that the results presented here should be taken with caution.



## August 20 - Raph notes

### Intro: I am still a bit bothered by some phrasing and transitions between paragraphs. But I think that everything that we want to say is there. 
### Methods: Good
### Results: Overall good. I could not decrease the size of the Figure 6a (the threshold figure). It would be great if you could have a look at it. Another thing: I still don;t know what to write for the description of the linear model. Since we are stating in the inferential criteria section in the Methods that we would make inference based on the coefficients of the model, should I add a table with the coefficient for the two models in the manuscript? In the supplementary materials? And if I don't add them to the manuscript, what should i say? Just describing the plots from visual inspection?
### Discussion: Paragraph 3 and 4 for sure need some rewriting, changing some sentences... 

Overall I think that the introduction and the discussion would need a good stab. But again, I think that everything that we want to say is there, but it definitely needs refining. I am working now on the Supplementary materials for this manuscript.

## Aug 27 - Rich notes

### Title

This could be simpler. Maybe:

Face recognition ability predicts the computational processes that support face recognition

Or

Linking face recognition ability to the computational processes that support face recognition

Or

Individual differences in the computational processes that support face recognition

(I think I like the last one so far as it seems simpler)

Some further notes on the title. 
I find it a little odd that we say face recognition ability predicts face recognition performance. 
I know that's partly what we study, but there is a truism to this that strikes me as an odd way to characterise our aims and findings. 
e.g., is it feasible that face recognition ability would NOT predict the comp processes of face recognition? I mean it is feasible that we would not detect anything for various reasons. But if the face recog test is valid, then surely it has to relate to another measure of a similar thing (another face recog task). Does this make sense?


Another option would be to focus on the how of the research...

How does face recognition ability shape the computational processes that support the identification of others?



### intro

Let's avoid the term "normal"

paragraph 3. I don't follow the logic of the second half of the paragraph. See my notes below. Can you clarify?

[[Raph - the importance and relevance for the next two sentences needs spelling out. See my comments in the Notes file.
e.g., why do the results support the conclusions that they do?
face AND general object in one sentence
face OR object in the next sentence??
But I don't understand the relevance for these claims in this para]]

cite preprints with a year e.g., 2026 rather than in press. 
This is because it is actually "published" in the sense that it is publically available for review and scrutiny.
in press is instead reserved for papers accepted at a journal but not yet out


### methods and results

I skimmed these sections to focus on the intro and discussion. 

However, I really like the figures and tables and general layout. 
I'm really not worried about the sizing issues that you highlight in your notes. 
I would just move on and fix it later if you think it is necessary.
I think they all look good and are very clear and that's the main thing.

As for the coefficients in the linear model, I'm not entirely sure what you are asking. 
Is this the distinction between coefficients and posterior predictions?
If so, I would just be clear in the method that we make posterior predictions and 95% QIs and interpret those. Cite a bunch of stuff for the benefits of doing so e.g., this book https://marginaleffects.com/, and these two papers https://doi.org/10.18637/jss.v111.i09, https://doi.org/10.1177/25152459261424825.

If you want to, you can then also report a table of coefficients in supps for the linear model or a table of posterior preds in the main text and/or supps. 

Maybe let's discuss in person??

I would definitely add some text in section 3.4 that describes the posterior preds (and have a table that summarises the posterior preds).
e.g., describe the visual patterns and QIs for an estimate of uncertainty in Figure 10a. This is one key result regarding our main question. 
Then just say that when we add in car recog, the results look almost identical with no meaningful change (Figure 10b).
That gives us our second inference - after adjusting for car recog, the pattern remains largely the same. inference = there is something about face recog blah blah...


One further comment on the results after reading the discussion. 
I would add much more narrative text that describes in simple words the patterns of results that you observed. 
This would mean that when you get to the discussion there is less need to re-state the patterns of results as they are already very clear.

One more thing. 
In Figures 7, 8 and 9, is there any need to show the car data?
e.g., our focus is face perception and we use car to adjust the regression model. 
But car recog in itself as a predictor of comp processes, is not really our interest.
So can we simplify the plots?

Basically, I think we need a way to help readers access and digest the pattern of results a little easier. 
These types of measures are not that common, and so folks need a little more help to guide them.

Is Figure 6 missing by the way? I cannot see it in the pdf.


### Discussion

I split up the discussion of drift rate and threshold into separate paragraphs, just to make things easier to read.

I also removed the below text because I think we can combine these two paras into one paragraph and make one point.
And that one point should be that we show value in looking at individual differences in latent computational processes.
I can help with this later. 

--- text removed 
Besides the insights obtained from the associations between individual differences and latent computational processes in the domain of face recognition, our choice of combining experimental, differential and computational methodologies has several implications for future differential studies, as well as for models of face perception and memory.
On a more general level, it offers a novel approach to investigate individual differences and expertise effects in face processing.
Most differential studies in face processing have used test scores to estimate different abilities underlying face processing and investigated if these abilities were related to each other or to other predictors of interest [@mccafferyIndividualDifferencesFace2018; @noyesFaceRecognitionAbility2018].
In this study we used traditional approach of an experimental manipulation in a large sample, extended the separate analysis of response times and accuracy to the estimation of latent variables through computational modelling that we then associated with face recognition ability.
The important difference with past investigations is that behavioral patterns (accuracy and response times) as well as latent variables patterns (LBA parameters) were associated with ability scores.
Using this approach allowed more specific hypotheses regarding which parts of the system is related to which type of recognition abilities, potentially aiding the development of theory.
We think that this approach could benefit future research on individual differences in visual recognition memory or visual perception more generally.

*Paragraph 4: Theoretical implications for models of face perception and memory*

Furthermore, we think that the insights obtained from this study could have theoretical implications for models of face perception and memory.
Previous individual differences studies in face recognition have investigated how different facets of the face recognition ability are associated across the normal population or differ between groups (ex: prosopagnosia and control/super-recognizer and control).
These findings extended the general cognitive model of the human face processing system (Bruce & Young, 1986), by showing that the performance (i.e response times and accuracy) to a face recognition task varies as a function of individual face recognition ability.
With this study we also contribute to the extension of this model by showing that not only there are individual differences in the performance, but that there is also individual differences in the cognitive processes that give rise to this outcome. Furthermore these differences vary to certain degree as function of individual face recognition ability. Cognitive processes are not measurable *per se* but cognitive models can be used to estimate certain of them. In order to extend our understanding of the different cognitive processes involved in face recognition and the potential differences across individuals in these processes, future research could benefit from combining different approaches (i.e. experimental, differential...) and different computational models.


Also, I think we should make the section on object recog abilities into one para, as it is currently two paras.
two paras out of 1000 words, is prop too much for an exploratory observation


## Sept 16

- Fix the Fournier REF consistently throughout to cite the preprint. 
- REFs missing para 1 Intro.
- I added some REFs on expertise at the end of the intro. The refs are as follows:

https://pmc.ncbi.nlm.nih.gov/articles/PMC10437139/

https://econtent.hogrefe.com/doi/10.1027/1618-3169/a000111

https://link.springer.com/article/10.3758/16.6.1026

https://doi.org/10.1525/collabra.160157


- In the results, much more detail is required in 2.7.2, 2.7.4. e.g., What exactly did you do in the classical correlational analysis? Could someone else reproduce what you did from what you've written? And in the linear regression, you need to explain the varying effects/intercepts structure and any other relevant information, like software used and functions maybe? e.g., brms?

- Results section. More narrative is required to remind the reader of the purpose of the analysis. 
e.g., 3.1 LBA.
We first estimated LBA params in individuals and at the group level.
The purpose of doing so was twofold. 
First, we needed subject specific estimates to address our primary RQs on indiv diffs.
Second, we also wanted to check that we found a similar pattern of results, as we observed in our prior work using the same task.
This is an important set to establish that the basic experimental effect is replicable at the group level before we pursue assessments of individual differences. 

- Figure 4 and 5 could be combined possibly then panel A and B.
the legend for Figures 4 and 5 needs working on. Much more detail required. 
- one question. would it make sense for Figs 4 and 5 to have 3 panels - with a new right panel that plots the distributions per PID? that would then visualise the variation in thresh and drift rate values? Or overplot individuals in a faint colour on the current right panels so that folks can easily see the variation. Or is it too much of a mess with all of those PIDs??

- Classic correlation analysis. You state the threshold results, but maybe add an extra sentence to explain what this means in simple terms. e.g., better face recogn ability is associated with blah, but the effect size is modest.

- Results. Figure 6. Big decision here. Also applies to the rest of the results. Do we present the car results in the main text? I kind of feel like it makes things harder and more complicated to understand. Our target aim (as we pre-registered) was all about face ability and then adjusting for car ability via regression. So one option would be to present the current car and face plots in Supps and only plot the face results in the main text. let's discuss this.

- 3.3 cite REFs for Bayesian plausible value correlations. - first sentence. 

- the choice of colours on Figure 6 and 7 is confusing. e.g., face vs car in one, but then the same colours are novel vs learned in another. Note - this could be much easier to deal with if we only present face in the main text.

- 3.4 linear regression. Say here how these results can be interpreted. e.g., as blah goes up, drift rate goes up for tue and down for false.  e.g., positive associaton vs negative association. Then say something about size, uncertainty, interval width etc.

- Table 4 I don't quite follow. some values seem to be repeated and the accuracy column makes no sense. Am I missing something here?

- Figure 6b. Change the order of panels. Make the far right panel be the contrast between TRUE - FALSE. Then the top row is learned and the bottom row is novel. That way you can easily see the progression from left to right.

However, now that I think about it, if we remove the car results from Figs 6, 7, 8, 9 and table 4 (and place them all in supps), then the Figure 6 can be even easier to plot. 
We can simply plot the scatter plot for novel and learned in one panel. 
That way we highlight the difference in slope (if any) between novel and learned for faces only, which is our main goal and finding. 
But we can show all of these plots in Supps so that we are consistent with our pre-reg. 
And we can make a comment that we visualise face results in the main text.
Then we can do the same in Figure 6b. 
We will present 3 panels instead of 6 - novel vs learned for true, false, and the true-false difference.
Does this make sense? I think it will be easier to digest.

And then we remove car plots from figs 7, 8, 9 also.

- Discussion - is this statement an accurate reflection of response caution. in other words, can we say this? : "who voluntary increase their response caution to ensure a better performance given the task demands"